### PR TITLE
[WIP] Action DSL

### PR DESCRIPTION
**Pull request by mateusg**
I prefer to handle this feature separated from the serializers subject.

So, I create this issue to post the action method:

``` ruby
class MyApiResource
  include Jeckle::Resource

  api :dribble # Any better idea on this?

  action :cancel,
    api: :workflow,
    method: :delete, # Optional, default => :get
    on: :member # Optional default => member
end
```

When developing the code, make sure to think in the objects, to become easily to evolve to get this feature later #33 

Profit!
## TO DO
- [x] Add `action` DSL with dynamic creation of action methods
- [x] Creation of collection actions
- [x] Creation of member actions
- [x] Support custom path, as the part of the endpoint that usually is the `action_name`
- [x] Support custom key (id, slug, etc) on member actions
- [x] Support a block on `params` options
  - [x] Does not send `attributes`
- [x] Support custom resource_name (#47) - name the option as `resource_path`
- [ ] Reuse action DSL to create `find` and `search` methods

To be done on further PRs:
- [ ] Support custom serializer option
  - [ ] Support root option (false, true or String)
- [ ] Support wildcards parsing when building the endpoint, such as `/posts/:id`. Figure out how to make it work with `key`
- [ ] Try to convert the resource `to_json` when the action is put/post/patch and no serializer is specified

Old TODOs:

> - Move HTTP stuff (like handle `Jeckle::Request`) and `action` methods definition to HTTP module
> - Move `resource_name` to `Jeckle::Resource`
> - Implement `action` DSL
> - Support custom `path`'s with wildcards
> - Support params (query string) with dynamic model attributes
> - Make `:api` options optional use resource's api as default
> - On PUT/POST/PATCH actions, use by default the serializer with the same name of the resource. For example: #Post resource will use PostSerializer

### CODE REVIEW

**Comment by mateusg** [comment]
This is a work in progress. It's just a sketch, I still have to improve lots of things and support more options.

**Comment by mateusg** [comment]
@brennovich The rubinius build is failing. Help, tolo.

**Comment by brennovich** [comment]
ooopsss

**Comment by mateusg** [comment]
:new_moon_with_face:

**Comment by tomas-stefano** [comment]
Until now :+1:

**Pull request closed without merging**
